
CREATE TABLE "user" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ROLES TEXT NULL
);

CREATE TABLE SECRETS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,
    SECRET TEXT NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    "user" BIGINT NOT NULL REFERENCES "user"(ID)
);

CREATE TABLE "group" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,

    "user" BIGINT NOT NULL REFERENCES "user"(ID)
);

CREATE TABLE JOB (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,
    START_DATE TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_DATE TIMESTAMP(10) NULL,
    FINISHED BOOLEAN NOT NULL DEFAULT FALSE,
    STATUS VARCHAR(100) NOT NULL,
    RESULT_MESSAGE TEXT NULL,

    "user" BIGINT NOT NULL REFERENCES "user"(ID),
    "group" BIGINT NULL REFERENCES "group"(ID)
);

CREATE TABLE JOB_UPDATE (
    ID SERIAL PRIMARY KEY,
    DATE TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PERCENT NUMERIC(3) NULL,
    LOG TEXT NULL,

    JOB BIGINT NOT NULL REFERENCES JOB(ID)
);

INSERT INTO "user"(NAME, EMAIL, PASSWORD, ROLES)
VALUES('Ricardo Poncio', 'ricardo.poncio@velsis.com.br', '123456', 'user, admin');