
CREATE TABLE "user" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ROLES TEXT NULL
);

CREATE TABLE SECRETS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,
    SECRET TEXT NOT NULL,

    DATE_START TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_END TIMESTAMP(10) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    "user" BIGINT NOT NULL REFERENCES "user"(ID)
);

CREATE TABLE "group" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,

    "user" BIGINT NOT NULL REFERENCES "user"(ID)
);

CREATE TABLE JOB (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL,
    START_DATE TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_DATE TIMESTAMP(10) NULL,
    FINISHED BOOLEAN NOT NULL DEFAULT FALSE,
    STATUS VARCHAR(100) NOT NULL,
    RESULT_MESSAGE TEXT NULL,

    "user" BIGINT NOT NULL REFERENCES "user"(ID),
    "group" BIGINT NULL REFERENCES "group"(ID)
);

CREATE TABLE JOB_UPDATE (
    ID SERIAL PRIMARY KEY,
    DATE TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PERCENT NUMERIC(3) NULL,
    LOG TEXT NULL,

    JOB BIGINT NOT NULL REFERENCES JOB(ID),
    SECRETS BIGINT NULL REFERENCES SECRETS(ID)
);

INSERT INTO "user"(NAME, EMAIL, PASSWORD, ROLES)
VALUES('Ricardo Poncio', 'ricardo.poncio@velsis.com.br', '$2a$10$2KzXmErqT.IGdfFKvva6A.Ut8heZR5.ctveYkz09eQMSQhq.zjMFS', 'user, admin');
-- Senha: 123456z

insert into secrets (name, description, secret, "user")
values('Test SSH', null, '5ab3afb3-5457-48cb-8460-1996cddb75cc', 1);