CREATE ROLE INCUSER WITH LOGIN ENCRYPTED PASSWORD 'dmVsc2lzY2x1c3Rlcmp1bGlhbm8=';
CREATE DATABASE INC;
GRANT CONNECT ON DATABASE INC TO INCUSER;
\connect inc
CREATE SCHEMA INC;
GRANT ALL PRIVILEGES ON SCHEMA INC TO INCUSER;
\connect postgres
SET SESSION AUTHORIZATION INCUSER;
SET search_path TO INC,public;
ALTER ROLE INCUSER SET search_path TO INC,public;
ALTER USER INCUSER WITH SUPERUSER;