CREATE TABLE SECRET_USE (
    ID SERIAL PRIMARY KEY,
    DATE TIMESTAMP(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    IP TEXT NULL,
    BROWSER TEXT NULL,
    BROWSER_VERSION TEXT NULL,
    OPERATING_SYSTEM TEXT NULL,
    DEVICE_TYPE TEXT NULL,

    ENDPOINT TEXT NULL,
    FILTER_PROCEED BOOLEAN NULL,

    "secret" BIGINT NOT NULL REFERENCES SECRETS(ID)
);